#!/usr/bin/env bash
#
# sync-roster.sh - regenerate roster.json from the EMPLOYEES array in index.html.
#
# WHY: the roster used to exist twice. index.html had the list the weekly
# scheduled task maintains, and kitchen-tasks.html had its own copy, which froze
# on 2026-04-22. By July it was still offering shifts to three people who had
# left and omitted eight who had joined -- and nobody noticed, because nothing
# compared the two.
#
# index.html stays the source of truth, because that is the file the weekly task
# already edits and we are not changing that task. This script copies the array
# into roster.json, which both pages read at runtime.
#
# Run by CI on every push that touches index.html, so the two cannot drift again.
# Safe to run by hand: it only rewrites roster.json when the list has changed.
#
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INDEX_HTML="$REPO_ROOT/index.html"
ROSTER_JSON="$REPO_ROOT/roster.json"

die() { printf 'sync-roster: ERROR: %s\n' "$*" >&2; exit 1; }
log() { printf 'sync-roster: %s\n' "$*"; }

[ -f "$INDEX_HTML" ] || die "index.html not found at $INDEX_HTML"
command -v python3 >/dev/null 2>&1 || die "python3 not found"

python3 - "$INDEX_HTML" "$ROSTER_JSON" <<'PY'
import json, re, sys, os

index_path, roster_path = sys.argv[1], sys.argv[2]
src = open(index_path, encoding='utf-8').read()

m = re.search(r'const\s+EMPLOYEES\s*=\s*\[(.*?)\];', src, re.S)
if not m:
    sys.exit("sync-roster: ERROR: could not find the EMPLOYEES array in index.html "
             "- did its shape change?")

names = re.findall(r'"([^"]+)"', m.group(1))
if not names:
    sys.exit("sync-roster: ERROR: EMPLOYEES array parsed as empty - refusing to "
             "write an empty roster, which would lock everyone out of the "
             "HACCP checklist.")

# Preserve the comment block and metadata if the file already exists, so the
# explanation of why this file is generated does not get stripped by CI.
existing = {}
if os.path.exists(roster_path):
    try:
        existing = json.load(open(roster_path, encoding='utf-8'))
    except Exception:
        existing = {}

out = {
    "_comment": existing.get("_comment") or [
        "Single source of truth for who works the Berlin kitchen.",
        "GENERATED by tools/sync-roster.sh from the EMPLOYEES array in index.html.",
        "Do not hand-edit."
    ],
    "kitchen": existing.get("kitchen", "Berlin"),
    "generatedFrom": "index.html EMPLOYEES",
    "employees": names,
}

new_text = json.dumps(out, indent=2, ensure_ascii=False) + "\n"
old_text = open(roster_path, encoding='utf-8').read() if os.path.exists(roster_path) else ""

if new_text == old_text:
    print(f"sync-roster: unchanged ({len(names)} employee(s))")
else:
    open(roster_path, 'w', encoding='utf-8').write(new_text)
    print(f"sync-roster: rewrote roster.json ({len(names)} employee(s)): "
          + ", ".join(names))
PY

exit_code=$?
[ "$exit_code" -eq 0 ] || exit "$exit_code"

if command -v git >/dev/null 2>&1 && git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
  if [ -n "$(git -C "$REPO_ROOT" status --short -- roster.json)" ]; then
    log "roster.json has uncommitted changes -- commit it with index.html"
  fi
fi
